import './App.css';
import Nav from './components/NavBar/Nav'
import Accueil from './components/accueil/Accueil'

function App() {
  return (
    <div className="App">
      <Nav/>
      <Accueil/>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
      <h1>Salut</h1>
    </div>
  );
}

export default App;
